dist: bionic

git:
  depth: 5

language: minimal

services:
  - docker

matrix:
  include:
    - env:
        - task=hadolint
      script:
        - docker run --rm -i hadolint/hadolint < Dockerfile
    - env:
        - task="Docker build"
      if: branch == master && (type != pull_request)
      script:
        - docker build --build-arg MAXMIND_LICENSE_KEY="$MAXMIND_LICENSE_KEY" -t ipinfo.tw:$TRAVIS_COMMIT .
      after_success:
        - docker images
